language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-yaml python3-gi gir1.2-gtk-3.0 psmisc
install:
  - python setup.py install
script: nosetests

